// 路由 meta 标题回填 —— 由 recon-gen-route-meta.mjs 从编译产物路由记录提取（勿手改）
// 用法：router 构建后按 route.name 补齐 meta.title（原版页面标题/标签页标题/面包屑末级）
export const ROUTE_TITLES = {
  AdminLogin: "后台登录",
  AdminDashboard: "工作台",
  AdminUsers: "用户管理",
  AdminRoles: "角色管理",
  AdminMenus: "菜单管理",
  AdminApis: "API管理",
  AdminDict: "字典管理",
  AdminAnnouncements: "通知管理",
  AdminArticles: "文章管理",
  AdminArticlesNew: "新增文章",
  AdminArticlesEdit: "编辑文章",
  AdminContent: "内容管理",
  AdminContentNew: "新增内容",
  AdminContentEdit: "编辑内容",
  AdminConfig: "配置管理",
  AdminResources: "资源文件",
  AdminMediaIcons: "图标管理",
  AdminMediaGallery: "图库管理",
  AdminLoginLogs: "登录历史",
  AdminOperationLogs: "操作历史",
  AdminTenants: "租户管理",
  AdminMonitorData: "数据监控",
  AdminMonitorServer: "服务监控",
  AdminMonitorCache: "缓存监控",
  AdminMonitorCacheList: "缓存列表",
  AdminMonitorPortalDevtoolsReport: "DevTools 上报",
  AdminMonitorPortalVisitHit: "门户访问打点",
  AdminMonitorPortalFeedback: "意见反馈",
  AdminMonitorIpAccessPolicy: "IP策略管理",
  AdminIpLocationCache: "IP地理信息",
  AdminLeagues: "联盟管理",
  AdminStadiumDistribution: "球场分布",
  AdminStadiums: "球场管理",
  AdminTeams: "球队管理",
  AdminLineupTemplates: "阵容模板",
  AdminCoaches: "教练管理",
  AdminPlayerList: "球员管理",
  AdminPlayerDetail: "球员详情",
  AdminPlayerClaimReview: "球员认证管理",
  AdminEvents: "赛事管理",
  AdminHistoryRecords: "沿革记录",
  AdminHighlightMoments: "高光时刻",
  AdminEventBracket: "对战详情",
  AdminGames: "赛程/结果",
  AdminGameNew: "录入比赛结果",
  AdminGameEdit: "编辑比赛结果",
  AdminGameLiveResume: "实时比赛录入",
  AdminGameLiveLineupGame: "确认先发阵容",
  AdminGameLiveWatch: "实时观赛",
  AdminGameDetail: "比赛详情",
  AdminGameLiveLineup: "确认先发阵容",
};

export const ROUTE_TITLE_KEYS = {
  PlatformDocsIndex: "route.platformDocs",
  PlatformArticleDetail: "route.articleDetail",
  NotFound: "route.notFound",
  ServiceUnavailable: "route.serviceUnavailable",
  PortalHome: "route.home",
  PortalArticleList: "route.news",
  PortalArticleDetail: "route.articleDetail",
  PortalEvents: "route.events",
  PortalGameDetail: "route.gameDetail",
  PortalTeams: "route.teams",
  PortalStarPlayers: "route.starPlayers",
  PortalTeamDetail: "route.teamDetail",
  PortalStadiumDetail: "route.stadiumDetail",
  PortalPlayerDetail: "route.playerDetail",
  PortalStats: "route.stats",
  PortalAnnouncementDoc: "route.announcementDoc",
  PortalAccountProfile: "route.accountProfile",
  PortalAccountLogin: "route.accountLogin",
  PortalRegister: "route.register",
  PortalForgotPassword: "route.forgotPassword",
  PortalPlayerClaimInvite: "route.playerClaimInvite",
};
